services:
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: sandbox-nmc-website-dev
    container_name: webserver-dev
    ports:
      - "8080:80"
    volumes:
      - ./nmc-website:/var/www/html/
    env_file:
      - ./id.env