name: Deploy to Server

on:
  push:
    branches:
      - main
    paths:
      - "nmc-website/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
    
      - name: Debug environment variables
        run: env | grep SSH

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: ssh -o StrictHostKeyChecking=no user@your-server-ip 'bash -s' < /home/nmcdev/sandbox-nmc-website/deploy.sh'
